[module.hugoVersion]
extended = true

[[module.imports]]
path = "github.com/hugomods/seo/modules/base"

[[module.imports]]
path = "github.com/hbstack/header"

[[module.imports]]
path = "github.com/hbstack/footer"

[[module.imports]]
path = "github.com/hugomods/icons/vendors/bootstrap"

[params.hb.base.full_width]
types = ["docs"]
# kinds = ["home"]
# sections = ["docs", "notes"]

[params.hb.terms]
paginate = 9
